name: instagram
description: An instagram clone.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.0.2+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^4.0.4
  firebase_auth: ^0.15.5+2
  scoped_model: ^1.0.1
  timeago: ^2.0.26
  firebase_database: ^3.1.3
  firebase_storage: ^3.1.3
  image_picker: ^0.6.3+4
  camera: ^0.5.7+4
  outline_material_icons: ^0.1.1
  path_provider: ^1.6.4
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    # icon from referred project
    - assets/icon/add_story.png
    - assets/icon/ic_add.png
    - assets/icon/ic_close.png
    - assets/icon/ic_comment.png
    - assets/icon/ic_grid.png
    - assets/icon/ic_heart.png
    - assets/icon/ic_home.png
    - assets/icon/ic_inbox.png
    - assets/icon/ic_like.png
    - assets/icon/ic_liked.png
    - assets/icon/ic_more.png
    - assets/icon/ic_profile.png
    - assets/icon/ic_save_black.png
    - assets/icon/ic_save.png
    - assets/icon/ic_savee_black.png
    - assets/icon/ic_search.png
    - assets/icon/ic_settings.png
    - assets/icon/story_delete.png
    - assets/icon/story_view.png
    # Resolution Aware Image Icons
    - assets/icon/1.5x/add_story.png
    - assets/icon/1.5x/ic_add.png
    - assets/icon/1.5x/ic_close.png
    - assets/icon/1.5x/ic_comment.png
    - assets/icon/1.5x/ic_grid.png
    - assets/icon/1.5x/ic_heart.png
    - assets/icon/1.5x/ic_home.png
    - assets/icon/1.5x/ic_inbox.png
    - assets/icon/1.5x/ic_like.png
    - assets/icon/1.5x/ic_liked.png
    - assets/icon/1.5x/ic_more.png
    - assets/icon/1.5x/ic_profile.png
    - assets/icon/1.5x/ic_save_black.png
    - assets/icon/1.5x/ic_save.png
    - assets/icon/1.5x/ic_savee_black.png
    - assets/icon/1.5x/ic_search.png
    - assets/icon/1.5x/ic_settings.png
    - assets/icon/1.5x/story_delete.png
    - assets/icon/1.5x/story_view.png
    - assets/icon/2.0x/add_story.png
    - assets/icon/2.0x/ic_add.png
    - assets/icon/2.0x/ic_close.png
    - assets/icon/2.0x/ic_comment.png
    - assets/icon/2.0x/ic_grid.png
    - assets/icon/2.0x/ic_heart.png
    - assets/icon/2.0x/ic_home.png
    - assets/icon/2.0x/ic_inbox.png
    - assets/icon/2.0x/ic_like.png
    - assets/icon/2.0x/ic_liked.png
    - assets/icon/2.0x/ic_more.png
    - assets/icon/2.0x/ic_profile.png
    - assets/icon/2.0x/ic_save_black.png
    - assets/icon/2.0x/ic_save.png
    - assets/icon/2.0x/ic_savee_black.png
    - assets/icon/2.0x/ic_search.png
    - assets/icon/2.0x/ic_settings.png
    - assets/icon/2.0x/story_delete.png
    - assets/icon/2.0x/story_view.png
    - assets/icon/3.0x/add_story.png
    - assets/icon/3.0x/ic_add.png
    - assets/icon/3.0x/ic_close.png
    - assets/icon/3.0x/ic_comment.png
    - assets/icon/3.0x/ic_grid.png
    - assets/icon/3.0x/ic_heart.png
    - assets/icon/3.0x/ic_home.png
    - assets/icon/3.0x/ic_inbox.png
    - assets/icon/3.0x/ic_like.png
    - assets/icon/3.0x/ic_liked.png
    - assets/icon/3.0x/ic_more.png
    - assets/icon/3.0x/ic_profile.png
    - assets/icon/3.0x/ic_save_black.png
    - assets/icon/3.0x/ic_save.png
    - assets/icon/3.0x/ic_savee_black.png
    - assets/icon/3.0x/ic_search.png
    - assets/icon/3.0x/ic_settings.png
    - assets/icon/3.0x/story_delete.png
    - assets/icon/3.0x/story_view.png
    - assets/icon/4.0x/add_story.png
    - assets/icon/4.0x/ic_more.png
    - assets/icon/4.0x/story_delete.png
    - assets/icon/4.0x/story_view.png
    # Resource Images
    - assets/res_image/logo.png
    - assets/res_image/placeholder.png
    - assets/res_image/mother_res.png
    - assets/res_image/logo_black.png
    - assets/res_image/logo_circle.png
    - assets/res_image/circle_gradient.png
    # Resource Icons
    - assets/res_icons/directOutline.png
    - assets/res_icons/userOutline.png
    - assets/res_icons/heartOutline.png
    - assets/res_icons/heartFilled.png
    - assets/res_icons/heartFilledRed.png
    - assets/res_icons/newPost.png
    - assets/res_icons/searchOutline.png
    - assets/res_icons/searchFilled.png
    - assets/res_icons/homeFilled.png
    - assets/res_icons/commentLike.png
    - assets/res_icons/saveOutline.png
    - assets/res_icons/commentOutline.png
    - assets/res_icons/cameraOutline.png
    - assets/res_icons/moreHorizontalOutline.png
    - assets/res_icons/homeOutline.png
    - assets/res_icons/userFilled.png
    - assets/res_icons/userFollowOutline.png
    - assets/res_icons/settingsOutline.png
    - assets/res_icons/addOutline.png
    - assets/res_icons/photoOutline.png
    - assets/res_icons/infoOutline.png
    - assets/res_icons/instagramOutline.png

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
