varlistOfString = [
    'directOutline',
    'userOutline',
    'heartOutline',
    'heartFilled',
    'heartFilledRed',
    'newPost',
    'searchOutline',
    'searchFilled',
    'homeFilled',
    'commentLike',
    'saveOutline',
    'commentOutline',
    'cameraOutline',
    #'typeLogo',
    'moreHorizontalOutline',
    'homeOutline',
    'userFilled',
    'userFollowOutline',
    'settingsOutline',
    #'photoGridActive',
    'profileSaveActive',
    #'profileTaggedActive',
    'addOutline',
    'photoOutline',
    'infoOutline',
    #'xStoriesOutline',
    #'close',
    'instagramOutline',
]
for i in varlistOfString:
    #print('''File('/storage/emulated/0/out/'''+i+'''.png').writeAsBytesSync(img.encodePng('''+i+'''));''')
    print('''   - assets/res_icon/'''+i+'.png')
